blank_issues_enabled: true
contact_links:
  - name: Documentation
    url: https://github.com/OhMyDitzzy/Yuki#readme
    about: Read the documentation for guides and examples
  - name: GitHub Discussions
    url: https://github.com/OhMyDitzzy/Yuki/discussions
    about: Ask questions and discuss ideas with the community